"""
models/doc_sections.py
~~~~~~~~~~~~~~~~~~~~~~
Data models representing the generated documentation report.
"""
from __future__ import annotations

from enum import Enum
from pathlib import Path

from pydantic import BaseModel, Field


class DiagramFormat(str, Enum):
    """Output format of generated diagrams."""

    MERMAID = "mermaid"


class Diagram(BaseModel):
    """An auto-generated diagram embedded in the documentation.

    Attributes:
        title:   Human-readable diagram title.
        format:  Diagram language/format (e.g. MERMAID).
        content: Raw diagram source code.
        caption: Optional descriptive caption shown below the diagram.
    """

    title: str
    format: DiagramFormat = DiagramFormat.MERMAID
    content: str
    caption: str | None = None


class DocSection(BaseModel):
    """A single section of the generated Markdown document.

    Attributes:
        heading:   Section heading text (used as Markdown `## Heading`).
        content:   Markdown-formatted body text.
        diagrams:  Any diagrams embedded within this section.
        order:     Numeric sort key controlling section order in the output.
    """

    heading: str
    content: str
    diagrams: list[Diagram] = Field(default_factory=list)
    order: int = 0


class DocReport(BaseModel):
    """The complete documentation report assembled by DocGenie.

    Attributes:
        repo_name:   Repository name (used for file naming and the doc title).
        repo_url:    Original GitHub URL.
        sections:    Ordered list of documentation sections.
        output_path: Where the final docs.md was saved.
    """

    repo_name: str
    repo_url: str
    sections: list[DocSection] = Field(default_factory=list)
    output_path: Path | None = None

    model_config = {"arbitrary_types_allowed": True}

    def to_markdown(self) -> str:
        """Render all sections into a single Markdown string.

        Returns:
            The complete Markdown document as a string.
        """
        lines: list[str] = [
            f"# {self.repo_name} — Documentation",
            "",
            f"> Generated by [Codebase Reader](https://github.com) from {self.repo_url}",
            "",
            "---",
            "",
        ]
        for section in sorted(self.sections, key=lambda s: s.order):
            lines.append(f"## {section.heading}")
            lines.append("")
            lines.append(section.content)
            lines.append("")
            lines.append("---")
            lines.append("")
        return "\n".join(lines)

